# Generated by cpp11: do not edit by hand

ContrastStatistics_draws <- function(draws, var2group_var, var2group_group, var2group_contrast, vargroupXcontrast, contrast_offsets, nsteps, maxBandwidth, summaryfun, mlog10pvalue_threshold, mlog10pvalue_hard_threshold_factor) {
  .Call(`_msglm_ContrastStatistics_draws`, draws, var2group_var, var2group_group, var2group_contrast, vargroupXcontrast, contrast_offsets, nsteps, maxBandwidth, summaryfun, mlog10pvalue_threshold, mlog10pvalue_hard_threshold_factor)
}

CloudsOverlap <- function(X, Y, maxBandwidth, nsteps, quant_probs) {
  .Call(`_msglm_CloudsOverlap`, X, Y, maxBandwidth, nsteps, quant_probs)
}

GammaMethodPValuesCombine <- function(pvalues, stt) {
  .Call(`_msglm_GammaMethodPValuesCombine`, pvalues, stt)
}
