# Generated by cpp11: do not edit by hand

ProbabilityLessSmoothed <- function(X, Y, nsteps, bandwidth) {
  .Call(`_msglm_ProbabilityLessSmoothed`, X, Y, nsteps, bandwidth)
}

DifferenceStatistics <- function(X, Y, Deltas, nsteps, maxBandwidth, matchIterations) {
  .Call(`_msglm_DifferenceStatistics`, X, Y, Deltas, nsteps, maxBandwidth, matchIterations)
}

ContrastStatistics <- function(X, var2group_var, var2group_group, var2group_contrast, contrastXvargroup, contrast_offsets, nsteps, maxBandwidth, summaryfun) {
  .Call(`_msglm_ContrastStatistics`, X, var2group_var, var2group_group, var2group_contrast, contrastXvargroup, contrast_offsets, nsteps, maxBandwidth, summaryfun)
}

CloudsOverlap <- function(X, Y, maxBandwidth, nsteps, quant_probs) {
  .Call(`_msglm_CloudsOverlap`, X, Y, maxBandwidth, nsteps, quant_probs)
}

GammaMethodPValuesCombine <- function(pvalues, stt) {
  .Call(`_msglm_GammaMethodPValuesCombine`, pvalues, stt)
}
