# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ProbabilityLessSmoothed <- function(X, Y, nsteps = 100L, bandwidth = NA_real_) {
    .Call('_msglm_ProbabilityLessSmoothed', PACKAGE = 'msglm', X, Y, nsteps, bandwidth)
}

DifferenceStatistics <- function(X, Y, Deltas, nsteps = 100L, maxBandwidth = NA_real_, matchIterations = TRUE) {
    .Call('_msglm_DifferenceStatistics', PACKAGE = 'msglm', X, Y, Deltas, nsteps, maxBandwidth, matchIterations)
}

ContrastStatistics <- function(X, experiments2conditions_experiment, experiments2conditions_condition, contrastXcondition, contrast_offsets, nsteps = 100L, maxBandwidth = NA_real_, quant_probs = as.numeric( c(0.025, 0.25, 0.50, 0.75, 0.975))) {
    .Call('_msglm_ContrastStatistics', PACKAGE = 'msglm', X, experiments2conditions_experiment, experiments2conditions_condition, contrastXcondition, contrast_offsets, nsteps, maxBandwidth, quant_probs)
}

CloudsOverlap <- function(X, Y, maxBandwidth = NA_real_, nsteps = 100L, quant_probs = as.numeric( c(0.025, 0.25, 0.50, 0.75, 0.975))) {
    .Call('_msglm_CloudsOverlap', PACKAGE = 'msglm', X, Y, maxBandwidth, nsteps, quant_probs)
}

GammaMethodPValuesCombine <- function(pvalues, stt) {
    .Call('_msglm_GammaMethodPValuesCombine', PACKAGE = 'msglm', pvalues, stt)
}

